// Generated by https://quicktype.io

export interface MenuHeader {
  menuItems: MenuItems;
}

export interface MenuItems {
  nodes: Node[];
}

export interface Node {
  id: string;
  path: string;
  label: string;
  cssClasses: string[];
}
